In [16]:
    import numpy as np  
      
    a = 50  
    b = 90  
      
    print("binary representation of a:",bin(a))  
    print("binary representation of b:",bin(b))  
    print("Bitwise-and of a and b: ",np.bitwise_or(a,b))  
    print(np.invert(5))
    print ('Left shift of 10 by two positions:') 
    print (np.left_shift(10,2))

binary representation of a: 0b110010
binary representation of b: 0b1011010
Bitwise-and of a and b:  122
-6
Left shift of 10 by two positions:
40


In [2]:
import numpy as np
a = np.array([10,20,30])
b = np.array([1,2,3])
print(a+b)
print(a.shape)
print(b.shape)
print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))

[11 22 33]
(3,)
(3,)
[11 22 33]
[ 9 18 27]
[10 40 90]
[10. 10. 10.]


In [5]:
import numpy as np 


print ( np.right_shift(40,2) )


10
