In [11]:
import numpy as np
a=np.array([1,2,3])
b=np.array([1,1,1])
print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))

[2 3 4]
[0 1 2]
[1 2 3]
[1. 2. 3.]


In [2]:
import numpy as np
a1=np.array([10,20,30])
b1=np.array([1,2,3,4])
print(a1+b1)

ValueError: operands could not be broadcast together with shapes (3,) (4,) 

In [7]:
import numpy as np
a1=np.array([[1,2],[3,4],[5,6]])
b1=np.array([10,20])
print(a1+b1)

[[11 22]
 [13 24]
 [15 26]]


In [5]:
import numpy as np
a1=np.array([[1,2,3],[5,6,7]])
b1=np.array([[10,20],[30,40]])
print(a1+b1)


ValueError: operands could not be broadcast together with shapes (2,3) (2,2) 

In [10]:
import numpy as np
a = np.array([0.0, 10.0, 20.0, 30.0])
b = np.array([[1.0, 2.0],[6.0, 3.0]])
print(a+b)

ValueError: operands could not be broadcast together with shapes (4,) (2,2) 

In [19]:
import numpy as np 
print( np.char.capitalize('hello world'))


Hello world


In [14]:
import numpy as np  
  
a = np.array([[2,10,20],[80,43,31],[22,44,10]])  
  
print("The original array:\n")  
print(a)  
print("Expected  Min Result:")  
print(np.amin(a,0))  
print(np.amin(a,1))
print("Expected  Max Result:") 
print(np.amax(a,0))
print(np.amax(a,1))  

The original array:

[[ 2 10 20]
 [80 43 31]
 [22 44 10]]
Expected  Min Result:
[ 2 10 10]
[ 2 31 10]
Expected  Max Result:
[80 44 31]
[20 80 44]


In [9]:
    import numpy as np  
      
    b = np.array([12, 90, 380, 12, 211])  
      
    print(np.where(b>12))  
      
    c = np.array([[20, 24],[21, 23]])  
      
    print(np.where(c>20))  

(array([1, 2, 4], dtype=int64),)
(array([0, 1, 1], dtype=int64), array([1, 0, 1], dtype=int64))
