In [2]:
!pip install numpy


You should consider upgrading via the 'c:\users\rockstar\appdata\local\programs\python\python39\python.exe -m pip install --upgrade pip' command.


In [5]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])

print(arr)

[1 2 3 4 5]


In [2]:
import numpy as np
print(np.__version__)

1.21.2


In [3]:
import numpy as np
myarray=np.array([1,2,3,4,5])
print(myarray)

[1 2 3 4 5]


In [4]:
import numpy as np
mylist=[1,2,3,4,5]
myarray=np.array(mylist)
print(myarray)

[1 2 3 4 5]


In [6]:
import numpy as np
myarray=np.array((1,2,3,4,5))
print(myarray)

[1 2 3 4 5]


In [7]:
import numpy as np
mytuple=(1,2,3,4,5)
myarray=np.array(mytuple)
print(myarray)

[1 2 3 4 5]


In [10]:
import numpy as np
arr = np.array([1, 2, 3, 4])
print(arr[1:3]) 


[2 3]


In [2]:
# printing original array
import numpy as np
arr = np.array([1, 2, 3, 4,5])
print ("The new created array is : ",end=" ")
for i in range (0,5):
    print (arr[i], end=" ")


The new created array is :  1 2 3 4 5 

In [5]:
import numpy as np
myarray=np.arange(5,6,2)
print(myarray)

[5]


In [20]:
import numpy as np
arr2 = np.arange(10,0,-2)
print(arr2)


[10  8  6  4  2]


In [10]:
import numpy as np
arr=np.empty((3,4),dtype=int)
print(arr)

[[4128860 6029375 7274573 7209077]
 [5242996 6881391 7602286 6357069]
 [6357102 6619239     114 3342437]]


In [11]:
import numpy as np
arr=np.zeros(3,dtype=int)
print(arr)

[0 0 0]


In [12]:
import numpy as np
arr=np.zeros((3,2),dtype=int)
print(arr)

[[0 0]
 [0 0]
 [0 0]]


In [13]:
import numpy as np
arr=np.ones(3,dtype=int)
print(arr)

[1 1 1]


In [14]:
import numpy as np
arr=np.ones((3,2),dtype=int)
print(arr)

[[1 1]
 [1 1]
 [1 1]]


In [7]:
import numpy as np
list1 = []
sum=0
a = int(input("Enter Size of array:"))
for i in range(a):
    list1.append(int(input("Enter Element:")))
myarray=np.array(list1)
print("Array elements are:")
for i in myarray:
    print(i)
print("Size:",myarray.size)
print("Sum of array elements are:")
for i in range(0,myarray.size):
    sum=sum+myarray[i]
print(sum)
   

Enter Size of array:3
Enter Element:10
Enter Element:20
Enter Element:30
Array elements are:
10
20
30
Size: 3
Sum of array elements are:
60


In [10]:
import numpy as np
list1 = []
a = int(input("Enter Size of array:"))
for i in range(a):
    list1.append(int(input("Enter Element:")))
    myarray=np.array(list1)
print(np.sum(myarray))

Enter Size of array:3
Enter Element:10
Enter Element:20
Enter Element:30
60


In [12]:
import numpy as np
list1 = []
sum=0
a = int(input("Enter Size of array:"))
for i in range(a):
    list1.append(int(input("Enter Element:")))
myarray=np.array(list1)
print("Array elements are:")
for i in myarray:
    print(i)
item = int(input("Enter item for search:"))
if item in myarray:
    print("Item found")
else:
    print("Item Not found")
    

Enter Size of array:3
Enter Element:11
Enter Element:12
Enter Element:13
Array elements are:
11
12
13
Enter item for search:32
Item Not found


In [4]:
import numpy as np
ar=np.array([1,2,4])
print(ar)

[1 2 4]


In [8]:
import numpy as np
myarray=np.array([ [1,1],[2,2],[3,3] ])
print(myarray)

[[1 1]
 [2 2]
 [3 3]]


In [17]:
#Addition of two matrix
import numpy as np
array3=np.empty((3,2), dtype = int)
print(array3)
array1=np.array([ [1,1],[2,2],[3,3] ])
array2=np.array([ [5,5],[5,5],[5,5] ])

for i in range(0,3):
    for j in range(0,2):
        array3[i][j]=array1[i][j]+array2[i][j]
print(array3)

        



[[5 5]
 [5 5]
 [5 5]]
[[6 6]
 [7 7]
 [8 8]]
